export const monthlyMealUsageListStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-5 py-6 sm:px-8 sm:py-10",
  container: "mx-auto w-full max-w-5xl",
  header: "flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between",
  eyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  title: "mt-2 text-2xl font-semibold tracking-[0.01em] text-[var(--text-primary)] sm:text-3xl",
  description: "mt-2 max-w-xl text-sm leading-6 text-[var(--text-secondary)]",
  controls: "grid w-full gap-3 sm:flex sm:w-auto sm:items-end",
  field: "grid gap-1.5",
  label: "text-xs font-semibold text-[var(--text-secondary)]",
  monthInput: "h-11 rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff]",
  reload: "inline-flex h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface)] disabled:cursor-not-allowed disabled:text-[var(--text-muted)]",
  settlementLink: "inline-flex h-11 items-center justify-center rounded-lg border border-[#b9c8ff] bg-[#f4f6ff] px-4 text-sm font-semibold text-[#244cda] transition-colors hover:border-[#8ea8ff] hover:bg-[#e9eeff] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2",
  pendingLink: "inline-flex h-11 items-center justify-center rounded-lg px-3 text-sm font-semibold text-[#244cda] underline decoration-[#b9c8ff] underline-offset-4 hover:text-[var(--accent)]",
  card: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  alert: "m-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  loadingNotice: "m-4 rounded-lg border border-[#cfdafe] bg-[#f4f6ff] px-3 py-3 text-sm leading-5 text-[#244cda]",
  total: "flex items-center justify-between gap-4 border-b border-[var(--border)] px-5 py-4 sm:px-6",
  totalLabel: "text-sm font-semibold text-[var(--text-secondary)]",
  totalAmount: "text-base font-semibold tabular-nums text-[var(--text-primary)]",
  state: "px-5 py-10 text-center sm:px-8",
  stateTitle: "text-base font-semibold text-[var(--text-primary)]",
  stateDescription: "mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--text-secondary)]",
  stateAction: "mt-5 inline-flex h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface)]",
  list: "divide-y divide-[var(--border)]",
  row: "grid gap-4 px-5 py-5 sm:px-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-start",
  partner: "text-sm font-semibold text-[var(--text-primary)]",
  customer: "mt-2 text-sm text-[var(--text-secondary)] [&_span]:mr-2 [&_span]:text-[var(--text-muted)]",
  side: "flex min-w-0 items-start justify-end gap-4 text-right md:block md:min-w-36",
  amount: "text-base font-semibold tabular-nums text-[var(--text-primary)]",
  statusBlock: "mt-1 flex flex-col items-end gap-1",
  confirmedInitials: "text-xs font-medium text-[var(--text-secondary)]",
  metadata: "text-sm text-[var(--text-secondary)] md:col-span-2",
  metadataLabel: "mr-2 text-[var(--text-muted)]",
  pager: "flex items-center justify-between gap-3 border-t border-[var(--border)] px-5 py-4 sm:px-6",
  pagerButton: "inline-flex h-11 min-w-24 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface)] disabled:cursor-not-allowed disabled:text-[var(--text-muted)]",
  pageLabel: "text-sm tabular-nums text-[var(--text-secondary)]",
  skeleton: "animate-pulse bg-[var(--surface-subtle)]",
};
