export const mealUsageListStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-5 py-6 sm:px-8 sm:py-10",
  container: "mx-auto w-full max-w-4xl",
  header: "flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between",
  headerActions: "flex items-center gap-2",
  eyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  title: "mt-2 text-2xl font-semibold tracking-[0.01em] text-[var(--text-primary)] sm:text-3xl",
  description: "mt-2 text-sm leading-6 text-[var(--text-secondary)]",
  refresh: "inline-flex h-11 shrink-0 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface)] disabled:cursor-not-allowed disabled:text-[var(--text-muted)]",
  monthlyLedgerLink: "inline-flex h-11 shrink-0 items-center justify-center rounded-lg px-3 text-sm font-semibold text-[#244cda] underline decoration-[#b9c8ff] underline-offset-4 hover:text-[var(--accent)]",
  card: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  notice: "m-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  incomingRefresh: "m-4 inline-flex min-h-11 w-[calc(100%-2rem)] items-center justify-center rounded-lg border border-[#cfdafe] bg-[#f4f6ff] px-3 py-2 text-sm font-semibold text-[#244cda] transition-colors hover:bg-[#edf1ff] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--accent)] disabled:cursor-not-allowed disabled:text-[#98abef]",
  statusNotice: "m-4 rounded-lg border border-[#cfdafe] bg-[#f4f6ff] px-3 py-3 text-sm leading-5 text-[#244cda]",
  successNotice: "m-4 flex min-w-0 items-start gap-3 rounded-xl border border-[#bde6ca] bg-[#effaf3] px-4 py-3 text-[#176b3a]",
  successIcon: "mt-0.5 size-5 shrink-0 stroke-current stroke-[2] [stroke-linecap:round] [stroke-linejoin:round]",
  successCopy: "min-w-0",
  successTitle: "break-words text-sm font-semibold leading-5 text-[#176b3a]",
  state: "px-5 py-10 text-center sm:px-8",
  stateTitle: "text-base font-semibold text-[var(--text-primary)]",
  stateDescription: "mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--text-secondary)]",
  stateAction: "mt-5 inline-flex h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface)]",
  list: "divide-y divide-[var(--border)]",
  row: "grid min-h-16 w-full grid-cols-[minmax(0,1fr)_auto] gap-x-4 gap-y-2 px-5 py-4 text-left transition-colors hover:bg-[var(--surface-subtle)] focus-visible:z-10 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[var(--accent)] disabled:cursor-not-allowed disabled:opacity-60 sm:grid-cols-[minmax(0,1fr)_8rem_auto] sm:items-center sm:px-6",
  selectedRow: "bg-[#f4f6ff] hover:bg-[#edf1ff]",
  metadata: "col-span-2 min-w-0 sm:col-span-1",
  source: "flex items-center gap-2 text-sm font-medium text-[var(--text-primary)]",
  sourceIconTablet: "size-6 shrink-0 stroke-current stroke-[1.75] text-[#315efb] [stroke-linecap:round] [stroke-linejoin:round]",
  sourceIconPartnerMobile: "size-6 shrink-0 stroke-current stroke-[1.75] text-[#6558d3] [stroke-linecap:round] [stroke-linejoin:round]",
  partner: "mt-1 block text-sm text-[var(--text-secondary)]",
  customer: "mt-1 block text-xs text-[var(--text-muted)]",
  createdAt: "mt-1 text-sm text-[var(--text-muted)]",
  amount: "self-start text-right text-base font-semibold tabular-nums text-[var(--text-primary)] sm:self-auto",
  status: "inline-flex w-fit self-start rounded-md bg-[#eef3ff] px-2 py-1 text-xs font-semibold text-[#244cda] sm:self-auto",
  confirmationPanel: "border-t border-[var(--border)] bg-[var(--surface-subtle)] px-5 py-5 sm:px-6",
  confirmationEyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  confirmationTitle: "mt-1 text-lg font-semibold text-[var(--text-primary)]",
  confirmationSummary: "mt-4 grid grid-cols-2 gap-3 rounded-xl border border-[var(--border)] bg-white p-4 text-sm sm:grid-cols-5 [&_div]:min-w-0 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:break-words [&_dd]:text-[var(--text-primary)]",
  confirmationAmount: "font-semibold tabular-nums text-[var(--text-primary)]",
  confirmationForm: "mt-5 max-w-sm",
  initialsLabel: "block text-sm font-semibold text-[var(--text-primary)]",
  initialsInputRow: "mt-2 flex items-center gap-2",
  initialsInput: "h-11 min-w-0 flex-1 rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:bg-[var(--surface)]",
  confirmIconAction: "inline-flex size-11 shrink-0 items-center justify-center rounded-lg bg-[var(--accent)] text-white transition-colors hover:bg-[#244cda] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--accent)] disabled:cursor-not-allowed disabled:bg-[#98abef]",
  rejectIconAction: "inline-flex size-11 shrink-0 items-center justify-center rounded-lg border border-[#efbbc2] bg-white text-[var(--danger)] transition-colors hover:bg-[#fff7f8] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--danger)] disabled:cursor-not-allowed disabled:text-[#d9a2aa]",
  terminalActionIcon: "size-5 stroke-current stroke-[2] [stroke-linecap:round] [stroke-linejoin:round]",
  confirmationError: "mt-3 text-sm leading-5 text-[var(--danger)]",
  confirm: "mt-4 inline-flex h-11 w-full items-center justify-center rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#244cda] disabled:cursor-not-allowed disabled:bg-[#98abef]",
  reconcile: "mt-4 inline-flex h-11 w-full items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface)] disabled:cursor-not-allowed disabled:text-[var(--text-muted)]",
  skeleton: "animate-pulse bg-[var(--surface-subtle)]",
};
