export const storePartnerRegistrationStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-4 py-6 sm:px-8 sm:py-10",
  container: "mx-auto w-full max-w-2xl",
  card: "rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[0_8px_30px_rgba(17,24,39,0.04)] sm:p-8",
  eyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  title: "mt-2 text-2xl font-semibold tracking-[0.01em] text-[var(--text-primary)] sm:text-3xl",
  description: "mt-2 max-w-xl text-sm leading-6 text-[var(--text-secondary)]",
  form: "mt-8 space-y-6",
  field: "space-y-2",
  label: "block text-sm font-semibold text-[var(--text-primary)]",
  hint: "text-xs leading-5 text-[var(--text-muted)]",
  input: "block h-12 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base text-[var(--text-primary)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:cursor-not-allowed disabled:bg-[var(--surface-subtle)] disabled:text-[var(--text-muted)]",
  choiceGrid: "grid gap-2 sm:grid-cols-2",
  choice: "flex min-h-12 cursor-pointer items-center gap-2 rounded-lg border border-[var(--border-strong)] px-3 text-sm text-[var(--text-primary)] has-[:checked]:border-[var(--accent)] has-[:checked]:bg-[#f4f6ff] has-[:checked]:font-semibold has-[:disabled]:cursor-not-allowed has-[:disabled]:opacity-60",
  error: "rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  notice: "rounded-lg border border-[#cfdafe] bg-[#f4f6ff] px-3 py-3 text-sm leading-5 text-[#244cda]",
  denied: "rounded-2xl border border-[#f1c7cd] bg-[#fff7f8] p-6 text-center",
  deniedTitle: "text-base font-semibold text-[var(--text-primary)]",
  deniedDescription: "mt-2 text-sm leading-6 text-[var(--text-secondary)]",
  actionRow: "flex flex-col-reverse gap-3 sm:flex-row sm:justify-end",
  secondaryAction: "inline-flex min-h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  primaryAction: "inline-flex min-h-11 items-center justify-center rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white hover:bg-[#244cda] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] disabled:cursor-not-allowed disabled:bg-[#9caeea]",
  link: "font-semibold text-[var(--accent)] underline underline-offset-4",
} as const;
