import motionStyles from "./Landing.motion.module.css";

export const landingStyles = {
  page: "min-h-dvh overflow-x-clip bg-[var(--canvas)] text-[var(--text-primary)]",
  header: "mx-auto flex w-full max-w-6xl items-center justify-between px-5 py-5 sm:px-8 sm:py-7 lg:px-12",
  headerBrand: "flex min-w-0 flex-col items-start",
  headerDescription: "mt-1 text-xs font-medium tracking-[-0.01em] text-[var(--text-secondary)] sm:text-sm",
  wordmarkLink: "inline-flex min-h-11 min-w-11 items-center justify-center rounded-md p-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-4",
  wordmarkMark: "h-auto w-[5.75rem] shrink-0 sm:w-[6.5rem]",
  tieatWordmark: "block overflow-visible",
  tieatWordmarkSide: "",
  tieatWordmarkFace: "fill-[#17181C]",
  tieatWordmarkEFace: "fill-[#315EFB]",
  tieatWordmarkDepth: "fill-[#8D96A7] opacity-[0.34]",
  tieatWordmarkDepthE: "fill-[#173FC4] opacity-[0.55]",
  tieatWordmarkHeaderDepth: "fill-[#8D96A7] opacity-[0.28]",
  tieatWordmarkHeaderDepthE: "fill-[#173FC4] opacity-[0.42]",
  tieatWordmarkCore: "",
  tieatWordmarkE: "",
  brandIntro: "pointer-events-none fixed inset-0 z-20 overflow-hidden",
  brandIntroMark: "absolute origin-center",
  brandIntroMarkSvg: "h-full w-full",
  heroBrand: "mb-8 w-fit max-w-full",
  heroBrandWordmark: "block h-auto w-[clamp(17rem,56vw,29rem)] max-w-full",
  headerLink: "inline-flex min-h-11 items-center rounded-md px-2 text-sm font-medium text-[var(--text-secondary)] underline decoration-[var(--border-strong)] underline-offset-4 transition-colors hover:text-[var(--accent)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-4",
  hero: "mx-auto grid w-full max-w-6xl items-center gap-12 px-5 pb-20 pt-10 sm:px-8 sm:pb-28 sm:pt-16 lg:grid-cols-[minmax(0,1fr)_minmax(320px,0.78fr)] lg:gap-20 lg:px-12 lg:pb-36 lg:pt-24",
  heroCopy: "max-w-2xl",
  eyebrow: "text-xs font-semibold uppercase tracking-[0.12em] text-[var(--accent)]",
  heroTitle: "mt-5 max-w-[32rem] text-[clamp(2.5rem,6.5vw,4.5rem)] font-light leading-[1.1] tracking-[0.002em] text-[var(--text-primary)]",
  heroDescription: "mt-7 max-w-xl text-base leading-7 text-[var(--text-secondary)] sm:text-lg sm:leading-8",
  heroActions: "mt-8 flex flex-col gap-3 sm:flex-row sm:items-center",
  primaryAction: `inline-flex min-h-12 w-full items-center justify-center gap-3 rounded-lg bg-[var(--accent)] px-5 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(49,94,251,0.18)] hover:bg-[#244cda] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2 sm:w-auto ${motionStyles.ctaPress}`,
  secondaryAction: `inline-flex min-h-12 w-full items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-5 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2 sm:w-auto ${motionStyles.ctaPress}`,
  heroNote: "mt-5 text-xs leading-5 text-[var(--text-muted)]",
  heroPreview: "relative mx-auto w-full max-w-md rounded-[1.25rem] border border-[var(--border)] bg-[var(--surface)] p-5 shadow-[0_18px_50px_rgba(17,24,39,0.06)] sm:p-7",
  previewTopline: "flex items-center gap-2 text-xs font-semibold tracking-[0.04em] text-[var(--text-secondary)]",
  previewDot: "size-2 rounded-full bg-[#176b3a]",
  previewDate: "ml-auto tabular-nums text-[var(--text-muted)]",
  previewAmount: "mt-9 flex items-end justify-between border-b border-[var(--border)] pb-5 text-sm text-[var(--text-secondary)]",
  previewRows: "divide-y divide-[var(--border)]",
  previewRow: "flex items-center justify-between gap-4 py-4 text-sm text-[var(--text-secondary)]",
  previewIcon: "mr-2 inline-grid size-6 place-items-center rounded-full bg-[#e9eeff] text-xs font-semibold text-[var(--accent)]",
  previewRowMuted: "flex items-center justify-between gap-4 pt-4 text-xs font-semibold text-[var(--accent)]",
  previewCaption: "mt-8 text-xs leading-5 text-[var(--text-muted)]",
  section: "mx-auto w-full max-w-6xl scroll-mt-8 px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36",
  sectionIntro: "max-w-2xl",
  sectionTitle: "mt-4 text-[clamp(2rem,5vw,3rem)] font-light leading-[1.2] tracking-[0.01em] text-[var(--text-primary)]",
  sectionDescription: "mt-5 max-w-xl text-base leading-7 text-[var(--text-secondary)]",
  flowGrid: "mt-12 grid gap-4 sm:grid-cols-3 sm:gap-5 lg:mt-16",
  flowLayout: "mt-12 grid gap-10 lg:mt-16 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.72fr)] lg:items-start lg:gap-16",
  flowSteps: "grid gap-4 sm:gap-5",
  flowCard: "relative min-h-52 rounded-2xl border bg-[var(--surface)] p-5 sm:p-6",
  flowCardIdle: "border-[var(--border)]",
  flowCardActive: "border-[var(--accent)] bg-white shadow-[0_14px_36px_rgba(49,94,251,0.12)] lg:-translate-y-0.5",
  flowNumber: "text-xs font-semibold tabular-nums tracking-[0.08em] text-[var(--accent)]",
  flowCurrentLabel: "absolute right-5 top-5 rounded-full bg-[#e9eeff] px-2.5 py-1 text-[0.68rem] font-semibold tracking-[0.02em] text-[var(--accent)] sm:right-6 sm:top-6",
  flowTitle: "mt-10 max-w-[15rem] text-xl font-medium tracking-[0.01em] text-[var(--text-primary)]",
  flowDescription: "mt-3 text-sm leading-6 text-[var(--text-secondary)]",
  mobileFlowPreview: "mt-6 lg:hidden",
  flowVisual: "hidden lg:block lg:self-stretch",
  flowVisualSticky: "sticky top-24",
  flowVisualShell: "pointer-events-none overflow-hidden rounded-[1.25rem] border border-[var(--border)] bg-[var(--surface-subtle)] p-5 shadow-[0_18px_50px_rgba(17,24,39,0.05)]",
  productPreview: "pointer-events-none rounded-[1rem] border border-[var(--border)] bg-white p-4",
  productPreviewTopline: "flex items-center justify-between border-b border-[var(--border)] pb-3",
  productPreviewLabel: "text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-[var(--text-muted)]",
  productPreviewScreen: "mt-4 rounded-[0.85rem] border border-[var(--border)] bg-[var(--surface)] p-4",
  productPreviewEyebrow: "text-[0.68rem] font-semibold tracking-[0.04em] text-[var(--accent)]",
  productPreviewTitle: "mt-2 text-base font-semibold leading-6 text-[var(--text-primary)]",
  productPreviewRows: "mt-4 divide-y divide-[var(--border)]",
  productPreviewRow: "flex items-center justify-between gap-4 py-2.5 text-xs text-[var(--text-secondary)]",
  productPreviewRowValue: "font-medium text-[var(--text-primary)]",
  productPreviewAmount: "mt-3 flex items-center justify-between rounded-lg bg-[#e9eeff] px-3 py-2.5 text-xs text-[var(--text-secondary)]",
  productPreviewAmountValue: "text-sm font-semibold tabular-nums text-[var(--accent)]",
  productPreviewStatus: "mt-4 flex items-center justify-start rounded-lg border border-[var(--border)] bg-white px-3 py-2.5 text-xs",
  productPreviewStatusLabel: "font-medium text-[var(--text-secondary)]",
  productPreviewField: "mt-3 flex items-center justify-between gap-4 rounded-lg border border-dashed border-[var(--border-strong)] px-3 py-2.5 text-xs",
  productPreviewFieldLabel: "text-[var(--text-muted)]",
  productPreviewFieldValue: "font-semibold tracking-[0.12em] text-[var(--text-primary)]",
  productPreviewAction: "mt-4 flex min-h-10 items-center justify-center rounded-lg bg-[var(--accent)] px-3 text-xs font-semibold text-white",
  productPreviewActions: "mt-4 grid grid-cols-2 gap-2",
  productPreviewRejectAction: "flex min-h-10 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-3 text-xs font-semibold text-[var(--text-secondary)]",
  productPreviewConfirmAction: "flex min-h-10 items-center justify-center rounded-lg bg-[var(--accent)] px-3 text-xs font-semibold text-white",
  productPreviewTotal: "mt-4 flex items-end justify-between border-b border-[var(--border)] pb-4",
  productPreviewTotalLabel: "text-xs text-[var(--text-secondary)]",
  productPreviewTotalValue: "text-lg font-semibold tabular-nums text-[var(--text-primary)]",
  productPreviewMetric: "flex items-center justify-between gap-4 py-2.5 text-xs",
  productPreviewMetricLabel: "text-[var(--text-secondary)]",
  productPreviewMetricValue: "font-semibold tabular-nums text-[var(--text-primary)]",
  productPreviewMetricAccent: "font-semibold tabular-nums text-[var(--accent)]",
  productPreviewLedgerAction: "mt-4 flex min-h-10 items-center justify-center rounded-lg border border-[var(--accent)] px-3 text-xs font-semibold text-[var(--accent)]",
  trustSection: "mx-auto grid w-full max-w-6xl gap-10 border-y border-[var(--border)] bg-[var(--surface-subtle)] px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1fr)] lg:gap-24 lg:px-12 lg:py-28",
  trustCopy: "max-w-xl",
  trustList: "grid content-start gap-4",
  trustItem: "flex gap-3 text-sm leading-6 text-[var(--text-secondary)]",
  trustMark: "mt-0.5 inline-grid size-5 shrink-0 place-items-center rounded-full bg-[#e4f3ed] text-xs font-bold text-[#176b3a]",
  contactSection: "mx-auto w-full max-w-6xl scroll-mt-8 px-5 py-20 sm:px-8 sm:py-28 lg:px-12 lg:py-36",
  contactCard: "grid gap-8 rounded-2xl border border-[var(--border-strong)] bg-white p-6 shadow-[0_8px_30px_rgba(17,24,39,0.04)] sm:p-10 lg:grid-cols-[minmax(0,1fr)_minmax(220px,0.55fr)] lg:items-end lg:gap-16",
  contactTitle: "mt-4 max-w-2xl text-[clamp(1.8rem,4vw,2.75rem)] font-light leading-[1.25] tracking-[0.01em] text-[var(--text-primary)]",
  contactDescription: "mt-5 text-base leading-7 text-[var(--text-secondary)]",
  contactStatus: "rounded-lg bg-[var(--surface-subtle)] px-4 py-3 text-sm leading-6 text-[var(--text-muted)]",
  footer: "border-t border-[#263149] bg-[#111827] px-5 py-12 text-white sm:px-8 sm:py-14 lg:px-12",
  footerInner: "mx-auto w-full max-w-6xl",
  footerTop: "flex flex-col gap-8 lg:flex-row lg:items-start lg:justify-between lg:gap-16",
  footerBrand: "inline-flex min-h-11 items-center gap-3 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-4 focus-visible:ring-offset-[#111827]",
  footerIcon: "size-9 shrink-0 rounded-[0.6rem]",
  footerBrandName: "text-lg font-semibold tracking-[0.08em] text-white",
  footerDescription: "mt-4 text-sm leading-6 text-slate-300",
  footerNav: "flex flex-wrap gap-2 sm:gap-3",
  footerNavLink: "inline-flex min-h-11 items-center rounded-md px-3 text-sm font-medium text-slate-200 transition-colors hover:bg-white/10 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-[#111827]",
  footerBottom: "mt-10 flex flex-col gap-2 border-t border-white/15 pt-5 text-xs leading-5 text-slate-400 sm:flex-row sm:items-center sm:justify-between sm:gap-6",
} as const;
