export const posSettlementFormStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-5 py-7 sm:px-8 sm:py-10",
  container: "mx-auto w-full max-w-5xl",
  header: "flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between",
  eyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  title: "mt-2 text-2xl font-semibold tracking-[0.01em] text-[var(--text-primary)] sm:text-3xl",
  description: "mt-2 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]",
  refresh: "inline-flex h-11 shrink-0 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:text-[var(--text-muted)]",
  card: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  state: "px-5 py-10 text-center sm:px-8",
  stateTitle: "text-base font-semibold text-[var(--text-primary)]",
  stateDescription: "mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--text-secondary)]",
  stateAction: "mt-5 inline-flex h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2",
  notice: "m-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  selectionHint: "m-4 rounded-xl border border-[#cfdafe] bg-[#f4f6ff] px-4 py-3 text-sm leading-5 text-[#244cda]",
  partnerList: "divide-y divide-[var(--border)]",
  partnerSection: "px-5 py-6 sm:px-6 sm:py-7",
  partnerHeader: "flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between",
  partnerTitle: "text-base font-semibold text-[var(--text-primary)]",
  partnerMeta: "mt-1 text-sm leading-6 text-[var(--text-secondary)]",
  partnerSummary: "grid gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4 text-sm sm:flex-1 sm:grid-cols-2 lg:grid-cols-3 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:tabular-nums [&_dd]:text-[var(--text-primary)]",
  partnerNote: "mt-3 text-xs leading-5 text-[var(--text-secondary)]",
  noPartnerReceivables: "mt-4 rounded-xl border border-dashed border-[var(--border-strong)] bg-[var(--surface-subtle)] px-4 py-4 text-sm leading-6 text-[var(--text-secondary)]",
  tableWrap: "overflow-x-auto",
  table: "min-w-full divide-y divide-[var(--border)] text-left text-sm",
  tableHeader: "bg-[var(--surface-subtle)] text-xs font-semibold tracking-[0.04em] text-[var(--text-muted)] [&_th]:px-4 [&_th]:py-3 sm:[&_th]:px-6",
  row: "border-b border-[var(--border)] last:border-0 hover:bg-[var(--surface-subtle)] [&_td]:px-4 [&_td]:py-4 sm:[&_td]:px-6 sm:[&_td]:py-5",
  disabledRow: "border-b border-[var(--border)] last:border-0 bg-[var(--surface-subtle)] opacity-60 [&_td]:px-4 [&_td]:py-4 sm:[&_td]:px-6 sm:[&_td]:py-5",
  checkbox: "size-5 rounded border-[var(--border-strong)] text-[var(--accent)] focus:ring-[var(--accent)] focus-visible:outline-none focus-visible:ring-2 disabled:cursor-not-allowed",
  primary: "font-medium text-[var(--text-primary)]",
  secondary: "mt-2 block text-xs leading-5 text-[var(--text-secondary)]",
  amount: "whitespace-nowrap text-right font-semibold tabular-nums text-[var(--text-primary)]",
  form: "border-t border-[var(--border)] bg-[var(--surface-subtle)] p-5 sm:p-7",
  formTitle: "text-base font-semibold text-[var(--text-primary)]",
  formDescription: "mt-1 text-sm leading-6 text-[var(--text-secondary)]",
  totals: "mt-4 grid gap-3 rounded-xl border border-[var(--border)] bg-white p-4 text-sm sm:grid-cols-2 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:tabular-nums [&_dd]:text-[var(--text-primary)]",
  fields: "mt-5 grid gap-4 sm:grid-cols-2",
  label: "block text-sm font-semibold text-[var(--text-primary)]",
  input: "mt-2 h-11 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:bg-[var(--surface)]",
  submit: "mt-5 inline-flex h-11 w-full items-center justify-center rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#244cda] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-[#98abef]",
  success: "m-5 rounded-xl border border-[#bde6ca] bg-[#effaf3] p-5 text-[#176b3a] sm:m-6",
  successTitle: "text-base font-semibold",
  successDescription: "mt-2 text-sm leading-6",
  allocationList: "mt-4 divide-y divide-[#bde6ca] rounded-lg border border-[#bde6ca] bg-white text-sm [&_li]:flex [&_li]:items-start [&_li]:justify-between [&_li]:gap-3 [&_li]:px-3 [&_li]:py-4",
  newSettlement: "mt-5 inline-flex h-11 items-center justify-center rounded-lg border border-[#8ccfa6] bg-white px-4 text-sm font-semibold text-[#176b3a] transition-colors hover:bg-[#f7fffa] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2",
  historyCard: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  historyHeader: "flex flex-col gap-4 border-b border-[var(--border)] px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6",
  historyTitle: "text-base font-semibold text-[var(--text-primary)]",
  historyDescription: "mt-1 max-w-2xl text-sm leading-6 text-[var(--text-secondary)]",
  historyList: "divide-y divide-[var(--border)]",
  historyItem: "px-5 py-5 sm:px-6",
  historyToggle: "block w-full rounded-lg p-1 text-left outline-none transition hover:bg-[var(--surface-subtle)] focus-visible:ring-2 focus-visible:ring-[var(--accent)]",
  historyRecord: "text-sm font-semibold text-[var(--text-secondary)]",
  historyItemTitle: "text-sm font-semibold text-[var(--text-primary)]",
  historyItemMeta: "mt-1 text-xs leading-5 text-[var(--text-secondary)]",
  historyDetail: "mt-4 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4",
  historyDetailGrid: "grid gap-3 text-sm sm:grid-cols-2 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:text-[var(--text-primary)]",
  historyAllocationList: "mt-4 divide-y divide-[var(--border)] rounded-lg border border-[var(--border)] bg-[var(--surface-subtle)] text-sm [&_li]:flex [&_li]:items-start [&_li]:justify-between [&_li]:gap-3 [&_li]:px-3 [&_li]:py-4",
  historyAllocationUsage: "break-all text-[var(--text-secondary)]",
};
