import { storeActionStyles } from "../StoreAction.styles";

export const posSettlementFormStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-5 py-7 sm:px-8 sm:py-10",
  container: "mx-auto w-full max-w-5xl",
  header: "flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between",
  title: "text-2xl font-semibold tracking-[0.01em] text-[var(--text-primary)] sm:text-3xl",
  refresh: `${storeActionStyles.neutral} h-11 shrink-0`,
  card: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  state: "px-5 py-10 text-center sm:px-8",
  stateTitle: "text-base font-semibold text-[var(--text-primary)]",
  stateDescription: "mx-auto mt-2 max-w-md text-sm leading-6 text-[var(--text-secondary)]",
  stateAction: `${storeActionStyles.neutral} mt-5`,
  notice: "m-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  selectionHint: "m-4 rounded-xl border border-[#cfdafe] bg-[#f4f6ff] px-4 py-3 text-sm leading-5 text-[#244cda]",
  partnerList: "divide-y divide-[var(--border)]",
  partnerSection: "px-5 py-6 sm:px-6 sm:py-7",
  partnerHeader: "flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between",
  partnerTitle: "text-base font-semibold text-[var(--text-primary)]",
  partnerMeta: "mt-1 text-sm leading-6 text-[var(--text-secondary)]",
  contractList: "mt-5 grid gap-4",
  contractSection: "rounded-xl border border-[var(--border)] bg-white p-4 sm:p-5",
  contractHeader: "flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between",
  contractTitle: "text-sm font-semibold text-[var(--text-secondary)]",
  partnerSummary: "grid gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4 text-sm sm:flex-1 sm:grid-cols-2 lg:grid-cols-3 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:tabular-nums [&_dd]:text-[var(--text-primary)]",
  noPartnerReceivables: "mt-4 rounded-xl border border-dashed border-[var(--border-strong)] bg-[var(--surface-subtle)] px-4 py-4 text-sm leading-6 text-[var(--text-secondary)]",
  tableWrap: "overflow-x-auto",
  table: "min-w-full divide-y divide-[var(--border)] text-left text-sm",
  tableHeader: "bg-[var(--surface-subtle)] text-xs font-semibold tracking-[0.04em] text-[var(--text-muted)] [&_th]:px-4 [&_th]:py-3 sm:[&_th]:px-6",
  row: "border-b border-[var(--border)] last:border-0 hover:bg-[var(--surface-subtle)] [&_td]:px-4 [&_td]:py-4 sm:[&_td]:px-6 sm:[&_td]:py-5",
  disabledRow: "border-b border-[var(--border)] last:border-0 bg-[var(--surface-subtle)] opacity-60 [&_td]:px-4 [&_td]:py-4 sm:[&_td]:px-6 sm:[&_td]:py-5",
  checkbox: "size-5 rounded border-[var(--border-strong)] text-[var(--accent)] focus:ring-[var(--accent)] focus-visible:outline-none focus-visible:ring-2 disabled:cursor-not-allowed",
  primary: "font-medium text-[var(--text-primary)]",
  secondary: "mt-2 block text-xs leading-5 text-[var(--text-secondary)]",
  amount: "whitespace-nowrap text-right font-semibold tabular-nums text-[var(--text-primary)]",
  form: "border-t border-[var(--border)] bg-[var(--surface-subtle)] p-5 sm:p-7",
  formTitle: "text-base font-semibold text-[var(--text-primary)]",
  formDescription: "mt-1 text-sm leading-6 text-[var(--text-secondary)]",
  totals: "mt-4 grid gap-3 rounded-xl border border-[var(--border)] bg-white p-4 text-sm sm:grid-cols-2 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:tabular-nums [&_dd]:text-[var(--text-primary)]",
  fields: "mt-5 grid gap-4 sm:grid-cols-2",
  label: "block text-sm font-semibold text-[var(--text-primary)]",
  input: "mt-2 h-11 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:bg-[var(--surface)]",
  submit: `${storeActionStyles.primary} mt-5 w-full`,
  success: "m-5 rounded-xl border border-[#bde6ca] bg-[#effaf3] p-5 text-[#176b3a] sm:m-6",
  successTitle: "text-base font-semibold",
  successDescription: "mt-2 text-sm leading-6",
  allocationList: "mt-4 divide-y divide-[#bde6ca] rounded-lg border border-[#bde6ca] bg-white text-sm [&_li]:flex [&_li]:items-start [&_li]:justify-between [&_li]:gap-3 [&_li]:px-3 [&_li]:py-4",
  receiptPanel: "mt-5 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4",
  receiptTitle: "text-sm font-semibold text-[var(--text-primary)]",
  receiptDescription: "mt-1 text-xs leading-5 text-[var(--text-secondary)]",
  receiptActions: "mt-3 flex flex-wrap items-center gap-3 [&_input[type=file]]:sr-only",
  receiptButton: `${storeActionStyles.neutral} cursor-pointer focus-within:outline-none focus-within:ring-2 focus-within:ring-[var(--focus)]`,
  receiptFileName: "mt-3 break-all text-xs leading-5 text-[var(--text-secondary)]",
  receiptMessage: "mt-3 text-sm leading-5 text-[var(--text-secondary)]",
  receiptPreview: "mt-4 overflow-hidden rounded-lg border border-[var(--border)] bg-white",
  receiptPreviewImage: "block max-h-[28rem] w-full object-contain",
  receiptPreviewFrame: "h-[28rem] w-full border-0",
  receiptPreviewMessage: "px-4 py-6 text-center text-sm leading-5 text-[var(--text-secondary)]",
  newSettlement: `${storeActionStyles.base} mt-5 h-11 border border-[#8ccfa6] bg-white px-4 text-[#176b3a] hover:bg-[#f7fffa]`,
  recordDialog: "fixed inset-0 z-50 m-0 flex max-h-dvh w-full max-w-full items-center justify-center bg-black/35 p-3 sm:p-5 [&::backdrop]:bg-black/35",
  recordDialogCard: "flex max-h-[calc(100dvh-1.5rem)] w-full max-w-xl flex-col overflow-hidden rounded-2xl bg-white shadow-[0_20px_60px_rgba(17,24,39,0.2)] sm:max-h-[calc(100dvh-2.5rem)]",
  recordDialogHeader: "flex shrink-0 items-start justify-between gap-4 border-b border-[var(--border)] p-5 sm:p-6",
  recordDialogTitle: "text-lg font-semibold text-[var(--text-primary)]",
  recordDialogPartner: "mt-1 break-words text-sm font-semibold text-[var(--text-secondary)]",
  recordDialogClose: `${storeActionStyles.neutral} shrink-0`,
  recordDialogBody: "min-h-0 overflow-y-auto p-5 sm:p-6",
  recordDialogForm: "mt-5 border-t border-[var(--border)] pt-5",
  recordDialogError: "mt-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  historyCard: "mt-6 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-[0_8px_30px_rgba(17,24,39,0.04)]",
  historyHeader: "flex flex-col gap-4 border-b border-[var(--border)] px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6",
  historyTitle: "text-base font-semibold text-[var(--text-primary)]",
  historyPageLabel: "text-sm font-medium tabular-nums text-[var(--text-secondary)]",
  historyDescription: "mt-1 max-w-2xl text-sm leading-6 text-[var(--text-secondary)]",
  historyFilters: "grid gap-3 border-b border-[var(--border)] bg-[var(--surface-subtle)] px-5 py-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] sm:items-end sm:px-6",
  historyFilterField: "grid gap-2 text-sm font-semibold text-[var(--text-primary)]",
  historyFilterControl: "h-11 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm font-normal text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff]",
  historyFilterActions: "flex flex-wrap items-center gap-2 sm:justify-end",
  historyFilterSubmit: `${storeActionStyles.primary} px-5`,
  historyFilterReset: storeActionStyles.neutral,
  historyList: "divide-y divide-[var(--border)]",
  historyItem: "px-5 py-5 sm:px-6",
  historyToggle: "block w-full rounded-lg p-1 text-left outline-none transition hover:bg-[var(--surface-subtle)] focus-visible:ring-2 focus-visible:ring-[var(--accent)]",
  historyRecord: "text-sm font-semibold text-[var(--text-secondary)]",
  historyItemTitle: "text-sm font-semibold text-[var(--text-primary)]",
  historyItemMeta: "mt-1 text-xs leading-5 text-[var(--text-secondary)]",
  historyDetail: "mt-4 rounded-xl border border-[var(--border)] bg-[var(--surface-subtle)] p-4",
  historyDetailGrid: "grid gap-3 text-sm sm:grid-cols-2 [&_dt]:text-[var(--text-muted)] [&_dd]:mt-1 [&_dd]:font-semibold [&_dd]:text-[var(--text-primary)]",
  historyAllocationList: "mt-4 divide-y divide-[var(--border)] rounded-lg border border-[var(--border)] bg-[var(--surface-subtle)] text-sm [&_li]:flex [&_li]:items-start [&_li]:justify-between [&_li]:gap-3 [&_li]:px-3 [&_li]:py-4",
  historyAllocationUsage: "break-all text-[var(--text-secondary)]",
  historyReceipt: "mt-4 flex flex-wrap items-center gap-x-3 gap-y-2 rounded-lg border border-[var(--border)] bg-white p-3",
  historyReceiptStatus: "text-sm font-semibold text-[var(--text-primary)]",
  historyReceiptMeta: "max-w-full break-all text-xs text-[var(--text-secondary)]",
  receiptDownload: "flex flex-wrap items-center gap-2",
};
