spring:
  application:
    name: tieat-api
  profiles:
    default: production
    group:
      retention:
        - production
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  session:
    jdbc:
      initialize-schema: never
      save-mode: on-set-attribute
    timeout: 30m
  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
