export const storeWorkspaceShellStyles = {
  workspace: "grid min-h-dvh bg-[var(--surface-subtle)] lg:grid-cols-[14rem_minmax(0,1fr)]",
  desktopSidebar: "sticky top-0 z-30 hidden h-dvh min-h-0 overflow-y-auto border-r border-[var(--border)] bg-white lg:block",
  sidebarInner: "flex min-h-full flex-col px-4 py-6",
  brand: "flex min-h-11 items-center px-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2",
  brandWordmark: "h-auto w-[6.5rem] shrink-0",
  brandDescription: "mt-1 px-2 text-xs font-medium leading-5 tracking-[-0.01em] text-[var(--text-secondary)]",
  storeName: "mt-6 px-2 pb-2 text-left text-lg font-semibold leading-7 break-words text-[var(--text-primary)]",
  navigation: "flex min-h-0 flex-1 flex-col",
  nav: "mt-8 grid gap-1",
  navLabel: "px-2 pb-2 text-[11px] font-semibold tracking-[0.08em] text-[var(--text-muted)]",
  navLink: "flex min-h-11 items-center rounded-lg px-3 text-sm font-medium text-[var(--text-secondary)] transition-colors hover:bg-[var(--surface-subtle)] hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  navLinkActive: "bg-[#edf2ff] font-semibold text-[var(--accent)] hover:bg-[#e7edff] hover:text-[var(--accent)]",
  directory: "mt-7 grid gap-1",
  kindFilter: "mx-2 mb-1 h-9 rounded-md border border-[var(--border)] bg-white px-2 text-xs text-[var(--text-secondary)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff]",
  directoryLink: "flex min-h-10 min-w-0 items-center rounded-lg px-3 text-sm text-[var(--text-secondary)] transition-colors hover:bg-[var(--surface-subtle)] hover:text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  directoryLinkActive: "bg-[#edf2ff] font-semibold text-[var(--accent)] hover:bg-[#e7edff] hover:text-[var(--accent)]",
  directoryName: "min-w-0 truncate",
  directoryStatus: "px-3 py-2 text-xs leading-5 text-[var(--text-muted)]",
  directoryError: "grid gap-2 px-3 py-2 text-xs leading-5 text-[var(--danger)]",
  retryButton: "inline-flex min-h-9 w-fit items-center rounded-md border border-[var(--border-strong)] bg-white px-2.5 text-xs font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  footerLinks: "mt-auto flex flex-col gap-2 pt-7 pb-3 lg:pb-0",
  pageBack: "bg-[var(--surface-subtle)] px-5 pt-6 sm:px-8 sm:pt-10",
  addLink: "flex min-h-11 items-center justify-center rounded-lg border border-[#b9c8ff] bg-[#f4f6ff] px-3 text-sm font-semibold text-[#244cda] transition-colors hover:border-[#8ea8ff] hover:bg-[#e9eeff] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  qrLink: "mt-2 flex min-h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  content: "min-w-0",
  mobileHeader: "sticky top-0 z-40 flex h-14 items-center justify-between border-b border-[var(--border)] bg-white/95 px-4 shadow-[0_4px_18px_rgba(17,24,39,0.05)] backdrop-blur supports-[backdrop-filter]:bg-white/85 lg:hidden",
  mobileBrand: "flex min-w-0 items-center gap-2 text-sm font-semibold tracking-[0.06em] text-[var(--text-primary)]",
  mobileWordmark: "h-auto w-[5.75rem] shrink-0",
  menuButton: "inline-flex h-10 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
  drawer: "m-0 h-dvh max-h-none w-[min(20rem,88vw)] max-w-none border-0 bg-white p-0 text-[var(--text-primary)] shadow-[8px_0_28px_rgba(17,24,39,0.18)] backdrop:bg-black/35 lg:hidden",
  drawerPanel: "flex h-full min-h-0 flex-col overflow-y-auto px-4 py-5",
  drawerHeader: "flex items-center justify-between gap-3 border-b border-[var(--border)] pb-4",
  drawerTitle: "text-base font-semibold text-[var(--text-primary)]",
  closeButton: "inline-flex h-10 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-3 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-subtle)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)]",
} as const;
