export const mealUsageQrFormStyles = {
  page: "min-h-dvh bg-[var(--surface-subtle)] px-5 py-8 sm:px-8 sm:py-12",
  container: "mx-auto w-full max-w-lg",
  eyebrow: "text-xs font-semibold tracking-[0.08em] text-[var(--accent)]",
  title: "mt-2 text-3xl font-semibold tracking-[0.01em] text-[var(--text-primary)]",
  description: "mt-3 text-sm leading-6 text-[var(--text-secondary)]",
  card: "mt-6 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[0_8px_30px_rgba(17,24,39,0.04)] sm:p-6",
  label: "mt-5 block text-sm font-semibold text-[var(--text-primary)] first:mt-0",
  select: "mt-2 h-12 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:bg-[var(--surface)]",
  input: "mt-2 h-12 w-full rounded-lg border border-[var(--border-strong)] bg-white px-3 text-base tabular-nums text-[var(--text-primary)] outline-none transition focus:border-[var(--accent)] focus:ring-2 focus:ring-[#dbe4ff] disabled:bg-[var(--surface)]",
  hint: "mt-2 text-sm leading-5 text-[var(--text-secondary)]",
  error: "mt-4 rounded-lg border border-[#f1c7cd] bg-[#fff7f8] px-3 py-3 text-sm leading-5 text-[var(--danger)]",
  submit: "mt-6 inline-flex h-12 w-full items-center justify-center rounded-lg bg-[var(--accent)] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#244cda] disabled:cursor-not-allowed disabled:bg-[#98abef]",
  retry: "mt-5 inline-flex h-11 items-center justify-center rounded-lg border border-[var(--border-strong)] bg-white px-4 text-sm font-semibold text-[var(--text-primary)] transition-colors hover:bg-[var(--surface)]",
  state: "rounded-2xl border border-[var(--border)] bg-white px-5 py-10 text-center shadow-[0_8px_30px_rgba(17,24,39,0.04)] sm:px-8",
  stateTitle: "text-lg font-semibold text-[var(--text-primary)]",
  stateDescription: "mx-auto mt-2 max-w-sm text-sm leading-6 text-[var(--text-secondary)]",
  success: "rounded-2xl border border-[#bde6ca] bg-[#effaf3] p-5 text-[#176b3a] shadow-[0_8px_30px_rgba(17,24,39,0.04)] sm:p-6",
  successTitle: "text-lg font-semibold",
  successAmount: "mt-4 text-3xl font-semibold tabular-nums",
  successDescription: "mt-3 text-sm leading-6 text-[#397d55]",
};
